/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.javaagent.instrumentation.spring.gateway.webmvc.v5_0;

import io.opentelemetry.api.common.AttributeKey;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.context.Context;
import io.opentelemetry.instrumentation.api.instrumenter.LocalRootSpan;
import io.opentelemetry.javaagent.bootstrap.internal.AgentInstrumentationConfig;
import java.net.URI;
import java.util.Optional;
import java.util.regex.Pattern;
import javax.annotation.Nullable;
import org.springframework.cloud.gateway.server.mvc.common.MvcUtils;
import org.springframework.web.servlet.function.ServerRequest;

/**
 * Helper class for extracting Spring Cloud Gateway Server WebMVC route information from
 * ServerRequest and adding it to spans.
 */
public final class ServerRequestHelper {

  /** Route ID attribute key. */
  private static final AttributeKey<String> ROUTE_ID_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.id");

  /** Route URI attribute key. */
  private static final AttributeKey<String> ROUTE_URI_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.uri");

  private static final boolean CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES;

  static {
    CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES =
        AgentInstrumentationConfig.get()
            .getBoolean(
                "otel.instrumentation.spring-cloud-gateway.experimental-span-attributes", false);
  }

  /* Regex for UUID */
  private static final Pattern UUID_REGEX =
      Pattern.compile(
          "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

  private ServerRequestHelper() {}

  public static void extractAttributes(
      Object gatewayRouterFunction, ServerRequest request, Context context) {
    if (!CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES) {
      return;
    }

    Span serverSpan = LocalRootSpan.fromContextOrNull(context);
    if (serverSpan == null) {
      return;
    }

    // Get route ID from the GatewayDelegatingRouterFunction field
    try {
      java.lang.reflect.Field routeIdField =
          gatewayRouterFunction.getClass().getDeclaredField("routeId");
      routeIdField.setAccessible(true);
      String routeId = (String) routeIdField.get(gatewayRouterFunction);
      String convergedRouteId = convergeRouteId(routeId);
      if (convergedRouteId != null) {
        serverSpan.setAttribute(ROUTE_ID_ATTRIBUTE, convergedRouteId);
      }
    } catch (Exception e) {
      // Silently ignore - field may not be accessible
    }

    // Get request URL (the target URI set by uri() filter)
    // Note: This is typically not available at the point when route() is called,
    // as filters execute later in the request processing chain
    Optional<Object> requestUrlOpt = request.attribute(MvcUtils.GATEWAY_REQUEST_URL_ATTR);
    requestUrlOpt.ifPresent(
        uri -> serverSpan.setAttribute(ROUTE_URI_ATTRIBUTE, ((URI) uri).toASCIIString()));
  }

  /** To avoid high cardinality, we ignore random UUID generated by Spring Cloud Gateway. */
  @Nullable
  private static String convergeRouteId(String routeId) {
    if (routeId == null || routeId.isEmpty()) {
      return null;
    }
    if (UUID_REGEX.matcher(routeId).matches()) {
      return null;
    }
    return routeId;
  }
}
