plugins {
  `java-library`
}

dependencies {
  compileOnly("javax.annotation:javax.annotation-api:1.3.2")
}

tasks {
  val generateInstrumentationVersionFile by registering {
    val name = computeInstrumentationName()
    val version = project.version as String
    inputs.property("instrumentation.name", name)
    inputs.property("instrumentation.version", version)

    val propertiesDir = layout.buildDirectory.dir("generated/instrumentationVersion/META-INF/io/opentelemetry/instrumentation/")
    outputs.dir(propertiesDir)

    doLast {
      val outputDir = propertiesDir.get().asFile
      outputDir.mkdirs()
      File(outputDir, "$name.properties").writeText("version=$version")
    }
  }

  val generateInstrumentationVersionClass by registering {
    val name = computeInstrumentationName()
    val version = project.version as String
    inputs.property("instrumentation.name", name)
    inputs.property("instrumentation.version", version)

    // The same logic is duplicated in EmbeddedInstrumentationProperties
    // Strip trailing version suffix and remove dashes.
    // If the module name contains a non-trailing version number e.g. jaxrs-3.0-jersey-3.0 replace
    // the dot with underscore. This is needed to turn the module name into valid package name, java
    // package name segments cannot start with a number.
    val moduleName = name.replace("(-[0-9.]*)$".toRegex(), "")
      .replace("-", "")
      .replace("([0-9]+)\\.([0-9]+)".toRegex(), "$1_$2")
    // Extract trailing version number and replace dots with underscores so it could be used as a
    // package name segment.
    val baseVersion = name.replace(".*?([0-9.]*)$".toRegex(), "$1")
      .replace(".", "_")
    val packageName = moduleName + if (baseVersion.isNotEmpty()) ".v$baseVersion" else ""

    val classDir = layout.buildDirectory.dir("generated/instrumentationVersionClass/${packageName.replace('.', '/')}/internal")
    outputs.dir(classDir)

    doLast {
      val outputDir = classDir.get().asFile
      outputDir.mkdirs()
      File(outputDir, "InstrumentationVersion.java").writeText("""
        package $packageName.internal;

        import javax.annotation.Generated;

        /** Autogenerated class do not edit. */
        @Generated("otel.instrumentation-version")
        public final class InstrumentationVersion {
          public static final String VERSION = "$version";

          private InstrumentationVersion() {}
        }
      """.trimIndent())
    }
  }

  project.tasks.matching { it.name == "compileJava" || it.name == "sourcesJar"
      || it.name == "compileKotlin" || it.name == "kotlinSourcesJar" }.configureEach {
    dependsOn(generateInstrumentationVersionFile, generateInstrumentationVersionClass)
  }

  named<Checkstyle>("checkstyleMain") {
    exclude("**/InstrumentationVersion.java")
  }
}

fun computeInstrumentationName(): String {
  val name = when (projectDir.name) {
    "javaagent", "library", "library-autoconfigure" -> projectDir.parentFile.name
    else -> project.name
  }
  return "io.opentelemetry.$name"
}

sourceSets {
  main {
    output.dir("build/generated/instrumentationVersion", "builtBy" to "generateInstrumentationVersionFile")
    java {
      srcDir(layout.buildDirectory.dir("generated/instrumentationVersionClass"))
    }
  }
}
