import kotlin.text.replace

plugins {
  `java-library`
}

tasks {
  val generateInstrumentationVersionFile by registering {
    val name = computeInstrumentationName()
    val version = project.version as String
    inputs.property("instrumentation.name", name)
    inputs.property("instrumentation.version", version)

    val propertiesDir = layout.buildDirectory.dir("generated/instrumentationVersion/META-INF/io/opentelemetry/instrumentation/")
    outputs.dir(propertiesDir)

    doLast {
      File(propertiesDir.get().asFile, "$name.properties").writeText("version=$version")
    }
  }

  val generateInstrumentationVersionClass by registering {
    val name = computeInstrumentationName()
    val version = project.version as String
    inputs.property("instrumentation.name", name)
    inputs.property("instrumentation.version", version)

    val moduleName = name.replace("(-[0-9.]*)$".toRegex(), "").replace("-", "").replace("([0-9]+)\\.([0-9]+)".toRegex(), "$1_$2")
    val baseVersion = name.replace(".*?([0-9.]*)$".toRegex(), "$1").replace(".", "_")
    val packageName = moduleName + if (baseVersion.isNotEmpty()) ".v$baseVersion" else ""

    val classDir = layout.buildDirectory.dir("generated/instrumentationVersionClass/${packageName.replace('.', '/')}/internal")
    outputs.dir(classDir)

    doLast {
      File(classDir.get().asFile, "InstrumentationVersion.java").writeText("""
        package $packageName.internal;

        // import javax.annotation.Generated;

        /** Autogenerated class do not edit. */
        // @Generated("otel.instrumentation-version")
        public final class InstrumentationVersion {
          public static final String VERSION = "$version";

          public InstrumentationVersion() {}

          @Override
          public String toString() {
            return VERSION;
          }
        }
      """.trimIndent())
    }
  }

  project.tasks.matching { it.name == "compileJava" || it.name == "sourcesJar"
      || it.name == "compileKotlin" || it.name == "kotlinSourcesJar" }.configureEach {
    dependsOn(generateInstrumentationVersionFile, generateInstrumentationVersionClass)
  }

  named<Checkstyle>("checkstyleMain") {
    exclude("**/InstrumentationVersion.java")
  }
}

fun computeInstrumentationName(): String {
  val name = when (projectDir.name) {
    "javaagent", "library", "library-autoconfigure" -> projectDir.parentFile.name
    else -> project.name
  }
  return "io.opentelemetry.$name"
}

sourceSets {
  main {
    output.dir("build/generated/instrumentationVersion", "builtBy" to "generateInstrumentationVersionFile")
    java {
      srcDir(layout.buildDirectory.dir("generated/instrumentationVersionClass"))
    }
  }
}
