/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.javaagent.instrumentation.spring.gateway.common;

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.common.AttributeKey;
import io.opentelemetry.instrumentation.api.incubator.config.internal.DeclarativeConfigUtil;
import java.util.regex.Pattern;
import javax.annotation.Nullable;

/**
 * Shared helper class for Spring Cloud Gateway instrumentation across different versions (WebFlux
 * and WebMVC).
 */
public final class GatewayRouteHelper {

  /** Route ID attribute key. */
  public static final AttributeKey<String> ROUTE_ID_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.id");

  /** Route URI attribute key. */
  public static final AttributeKey<String> ROUTE_URI_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.uri");

  /** Route order attribute key. */
  public static final AttributeKey<Long> ROUTE_ORDER_ATTRIBUTE =
      AttributeKey.longKey("spring-cloud-gateway.route.order");

  /** Route filter size attribute key. */
  public static final AttributeKey<Long> ROUTE_FILTER_SIZE_ATTRIBUTE =
      AttributeKey.longKey("spring-cloud-gateway.route.filter.size");

  private static final boolean CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES;

  static {
    CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES =
        DeclarativeConfigUtil.getBoolean(
                GlobalOpenTelemetry.get(), "spring_cloud_gateway", "span_attributes/development")
            .orElse(false);
  }

  /* Regex for UUID */
  private static final Pattern UUID_REGEX =
      Pattern.compile(
          "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

  private static final String INVALID_RANDOM_ROUTE_ID =
      "org.springframework.util.AlternativeJdkIdGenerator@";

  private GatewayRouteHelper() {}

  /** Returns whether experimental span attributes should be captured. */
  public static boolean shouldCaptureExperimentalSpanAttributes() {
    return CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES;
  }

  /**
   * To avoid high cardinality, we ignore random UUID generated by Spring Cloud Gateway. Spring
   * Cloud Gateway generates invalid random routeID, and it is fixed until 3.1.x
   *
   * @see <a
   *     href="https://github.com/spring-cloud/spring-cloud-gateway/commit/5002fe2e0a2825ef47dd667cade37b844c276cf6">Spring
   *     Cloud Gateway commit</a>
   */
  @Nullable
  public static String convergeRouteId(@Nullable String routeId) {
    if (routeId == null || routeId.isEmpty()) {
      return null;
    }
    if (UUID_REGEX.matcher(routeId).matches()) {
      return null;
    }
    if (routeId.startsWith(INVALID_RANDOM_ROUTE_ID)) {
      return null;
    }
    return routeId;
  }
}
