[global]
disable = ["MD059", "line-length", "no-inline-html", "MD041", "MD022", "ul-style", "fenced-code-language"]

[no-duplicate-heading]
siblings-only = true

[no-trailing-punctuation]
punctuation = ".,;:"

[ol-prefix]
style = "ordered"
