# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# and https://github.com/DavidAnson/markdownlint-cli2
[global]
# disable link text should be descriptive check
disable = ["MD059", "line-length", "no-inline-html", "MD041", "MD022", "ul-style", "fenced-code-language"]

[no-duplicate-heading]
siblings-only = true

[no-trailing-punctuation]
# allowing exclamation points and question marks at end of sentences
punctuation = ".,;:"

[ol-prefix]
style = "ordered"
