file_format: "1.1"

instrumentation/development:
  java:
    common:
      v3_preview: true

distribution:
  javaagent:
    # enabling v3_preview should enable this
    # indy/development: true
    force_synchronous_agent_listeners/development: false
    thread_details_enabled: true
    exclude_classes:
      - com.example.excluded.Class1
      - com.example.excluded.Class2
    exclude_class_loaders:
      - com.example.ExcludedClassLoader
    instrumentation:
      enabled:
        - tomcat
        - spring_webmvc
        - armeria
      disabled:
        - armeria_grpc
