file_format: "1.0-rc.1"

distribution:
  javaagent:
    indy/development: true
    exclude_classes:
      - com.example.excluded.Class1
      - com.example.excluded.Class2
    exclude_class_loaders:
      - com.example.ExcludedClassLoader
    additional_library_ignores:
      - com.example.ignored.Library
    instrumentation:
      default_enabled: false
      enabled:
        - tomcat
        - spring-webmvc
