contact_links:
  - name: GitHub Discussions
    url: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/new/choose
    about: Please ask questions here.
  - name: StackOverflow
    url: https://stackoverflow.com/questions/ask?tags=open-telemetry+java
    about: Or on StackOverflow.
  - name: Slack
    url: https://cloud-native.slack.com/archives/C014L2KCTE3
    about: Or the `#otel-java` channel in the CNCF Slack instance.
