/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.instrumentation.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GenerateInstrumentationVersionClassTask : DefaultTask() {
  @get:Input
  abstract val className: Property<String>

  @get:Input
  abstract val instrumentationVersion: Property<String>

  @get:OutputDirectory
  abstract val outputDirectory: DirectoryProperty

  @TaskAction
  fun generate() {
    val configuredClassName = className.get()
    val lastDotIndex = configuredClassName.lastIndexOf('.')
    require(lastDotIndex > 0 && lastDotIndex < configuredClassName.length - 1) {
      "instrumentationVersionClass.className must be a fully qualified class name"
    }

    val packageName = configuredClassName.substring(0, lastDotIndex)
    val simpleClassName = configuredClassName.substring(lastDotIndex + 1)
    val outputRoot = outputDirectory.get().asFile
    outputRoot.deleteRecursively()
    val outputDir = outputRoot.resolve(packageName.replace('.', '/'))
    outputDir.mkdirs()
    outputDir.resolve("$simpleClassName.java").writeText(
      """
      package $packageName;

      /** Autogenerated class. Do not edit. */
      public final class $simpleClassName {
        public static final String VERSION = "${instrumentationVersion.get()}";

        private $simpleClassName() {}
      }
      """.trimIndent()
    )
  }
}
