/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package com.example.javaagent;

// This class is generated by build.gradle.  Do not edit.

public class DistributionVersion {

  public static final String VERSION = "1.0-SNAPSHOT";
}
