import aQute.bnd.gradle.Bundle
import aQute.bnd.gradle.Resolve
import aQute.bnd.gradle.TestOSGi
import org.gradle.api.artifacts.ExternalModuleDependency
import org.gradle.api.artifacts.component.ModuleComponentIdentifier
import java.util.jar.JarFile

plugins {
  id("otel.java-conventions")
}

description = "OpenTelemetry Instrumentation OSGi Integration Tests"

// Verifies that the OSGi bundle metadata generated by otel.osgi-conventions actually resolves and
// runs in a real OSGi container (Apache Felix), with ServiceLoader mediation provided by Aries
// SPI Fly. Mirrors opentelemetry-java's integration-tests/osgi.
//
// For similar test examples see:
// https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-osgi-test
// https://github.com/eclipse-osgi-technology/osgi-test/tree/main/examples/osgi-test-example-gradle

// OSGi test infrastructure shared across all suites. Each suite's source set inherits these via
// registerOsgiSuite().
val osgiInfraImplementation: Configuration = configurations.create("osgiInfraImplementation") {
  isCanBeResolved = false
  isCanBeConsumed = false
}
val osgiInfraRuntimeOnly: Configuration = configurations.create("osgiInfraRuntimeOnly") {
  isCanBeResolved = false
  isCanBeConsumed = false
}

dependencies {
  // Tests use JUnit's built-in assertions rather than assertj: assertj imports net.bytebuddy
  // mandatorily, and byte-buddy 1.18.10's multi-release jar advertises a JavaSE-24 execution
  // environment requirement that the JavaSE-21 OSGi runtime can't satisfy.
  osgiInfraImplementation("org.junit.jupiter:junit-jupiter")
  osgiInfraImplementation("org.osgi:org.osgi.test.junit5")
  osgiInfraRuntimeOnly("org.junit.platform:junit-platform-launcher")
  osgiInfraRuntimeOnly("org.apache.felix:org.apache.felix.framework")
  osgiInfraRuntimeOnly("org.apache.aries.spifly:org.apache.aries.spifly.dynamic.bundle")
}

/** Typed dependency scope for an OSGi test suite, avoiding stringly-typed invoke() calls. */
class OsgiSuiteDependencies(private val sourceSet: SourceSet, private val handler: DependencyHandler) {
  fun implementation(notation: Any) = handler.add(sourceSet.implementationConfigurationName, notation)
  fun compileOnly(notation: Any) = handler.add(sourceSet.compileOnlyConfigurationName, notation)
  fun runtimeOnly(notation: Any) = handler.add(sourceSet.runtimeOnlyConfigurationName, notation)

  fun implementation(notation: String, configure: ExternalModuleDependency.() -> Unit) {
    (handler.add(sourceSet.implementationConfigurationName, notation) as ExternalModuleDependency).configure()
  }
}

/**
 * Registers tasks for an OSGi test suite (TestingBundle, GenerateBndrun, Resolve, testOSGi<Name>)
 * with a corresponding source set under src/test<Name>/java.
 *
 * @param extraRunrequires `bnd.identity` entries added to `-runrequires` to force bundles into the
 *   Felix runtime that the BND resolver won't pull in automatically.
 * @param extraRunsystempackages Package prefixes of non-OSGi classpath libraries to expose via
 *   `-runsystempackages`. Versions are resolved dynamically from the runtime classpath.
 * @param serviceLoaderProvides SPI types that the testing bundle provides via META-INF/services
 *   (noop test implementations). Generates Provide-Capability + Require-Capability registrar so
 *   SPI Fly picks them up.
 * @param minJavaVersion If set, skips the suite when `testJavaVersion` is below this value.
 * @param resolveOnly When true, the suite stops at BND resolution (proving the bundle's OSGi wiring
 *   is satisfiable) and does not boot the container. Use when the instrumented library's own OSGi
 *   bundles have runtime packaging quirks that are provided/handled by the target platform.
 */
fun registerOsgiSuite(
  suiteName: String,
  extraRunrequires: List<String> = emptyList(),
  extraRunsystempackages: List<String> = emptyList(),
  serviceLoaderProvides: List<String> = emptyList(),
  minJavaVersion: Int? = null,
  resolveOnly: Boolean = false,
  configureDependencies: OsgiSuiteDependencies.() -> Unit = {},
): TaskProvider<out Task> {
  val sourceSet = sourceSets.create("test${suiteName.replaceFirstChar { it.uppercase() }}")
  OsgiSuiteDependencies(sourceSet, dependencies).configureDependencies()

  // Inherit shared OSGi test infrastructure.
  configurations[sourceSet.implementationConfigurationName].extendsFrom(osgiInfraImplementation)
  configurations[sourceSet.runtimeOnlyConfigurationName].extendsFrom(osgiInfraRuntimeOnly)
  // osgi.core is compile-only (provided by the OSGi container at runtime). extendsFrom does not
  // propagate to custom source set compile classpaths, so we add it directly.
  dependencies.add(sourceSet.compileOnlyConfigurationName, "org.osgi:osgi.core")

  if (minJavaVersion != null) {
    configurations[sourceSet.runtimeClasspathConfigurationName].attributes {
      attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, minJavaVersion)
    }
  }

  val bsn = "opentelemetry-osgi-testing-$suiteName"

  val bundleTask = tasks.register<Bundle>("${suiteName}TestingBundle") {
    archiveClassifier.set("testing-$suiteName")
    from(sourceSet.output)
    bundle {
      // The Bundle task uses compileClasspath by default for BND analysis (e.g. resolving the
      // @Testable annotation to populate Test-Cases). Without this, testImplementation dependencies
      // like junit-jupiter are invisible to BND, causing Test-Cases to be empty and 0 tests to run.
      classpath(sourceSet.runtimeClasspath)
      val bndArgs = mutableListOf(
        "Bundle-SymbolicName: $bsn",
        "Test-Cases: \${classes;HIERARCHY_INDIRECTLY_ANNOTATED;org.junit.platform.commons.annotation.Testable;CONCRETE}",
      )
      if (serviceLoaderProvides.isNotEmpty()) {
        bndArgs.add("Provide-Capability: ${serviceLoaderProvides.joinToString(",") { "osgi.serviceloader;osgi.serviceloader=\"$it\"" }}")
        bndArgs.add("Require-Capability: osgi.extender;filter:=\"(osgi.extender=osgi.serviceloader.registrar)\"")
      }
      bnd(*bndArgs.toTypedArray())
    }
  }

  val runee = "JavaSE-${java.toolchain.languageVersion.get()}"

  // opentelemetry-instrumentation-api imports io.opentelemetry.semconv, but the upstream semconv
  // jar is not an OSGi bundle, so expose it as a system package for every suite.
  val effectiveRunsystempackages = extraRunsystempackages + "io.opentelemetry.semconv|opentelemetry-semconv"

  // Build the "-runpath" / "-runsystempackages" bndrun lines that expose non-OSGi jars (e.g. the
  // upstream semconv jar) to the OSGi runtime. Resolved lazily at execution time (configuration-cache
  // safe; the lambda captures only effectiveRunsystempackages). These must be in the bndrun *before*
  // resolution so the resolver can satisfy mandatory imports of non-OSGi jars (e.g. instrumentation-api's
  // mandatory import of io.opentelemetry.semconv). Entries use "packagePrefix|artifactNamePrefix" when
  // the package and artifact names differ.
  val systemPackagesContent = configurations.named(sourceSet.runtimeClasspathConfigurationName)
    .flatMap { it.incoming.artifacts.resolvedArtifacts }
    .map { artifacts ->
      val entries = effectiveRunsystempackages
      val byModule = artifacts.mapNotNull { art ->
        (art.id.componentIdentifier as? ModuleComponentIdentifier)?.let { it to art.file }
      }
      val runpath = mutableListOf<String>()
      val systemPackages = mutableListOf<String>()
      for (entry in entries) {
        val parts = entry.split("|")
        val packagePrefix = parts[0]
        val artifactPrefix = (if (parts.size > 1) parts[1] else packagePrefix).trimEnd { c -> c.isDigit() }.lowercase()
        for ((id, file) in byModule.filter { it.first.module.lowercase().startsWith(artifactPrefix) }) {
          val mainAttributes = JarFile(file).use { it.manifest?.mainAttributes }
          val bsn = mainAttributes?.getValue("Bundle-SymbolicName")?.substringBefore(';')?.trim()
          // The system bundle advertises the package at the jar's real (Maven) version.
          systemPackages += "$packagePrefix;version=${id.version}"
          // bnd indexes a real OSGi bundle by its Bundle-SymbolicName/Bundle-Version, but a plain jar
          // (no manifest headers) by its Maven group id at version 0.0.0.
          runpath += if (bsn != null) {
            "$bsn;version=${mainAttributes.getValue("Bundle-Version") ?: id.version}"
          } else {
            "${id.group};version=0.0.0"
          }
        }
      }
      buildString {
        val distinctRunpath = runpath.distinct()
        if (distinctRunpath.isNotEmpty()) append("\n-runpath: ${distinctRunpath.joinToString(", ")}")
        if (systemPackages.isNotEmpty()) append("\n-runsystempackages: ${systemPackages.distinct().joinToString(", ")}")
      }
    }

  val inputBndrun = layout.buildDirectory.file("bndrun/$suiteName.bndrun")
  val generateBndrunTask = tasks.register("${suiteName}GenerateBndrun") {
    inputs.property("bsn", bsn)
    inputs.property("runee", runee)
    inputs.property("extraRunrequires", extraRunrequires)
    inputs.property("systemPackagesContent", systemPackagesContent)
    outputs.file(inputBndrun)
    doLast {
      val extraEntries = extraRunrequires.joinToString("") { ",\\\n|  bnd.identity;id='$it'" }
      inputBndrun.get().asFile.apply { parentFile.mkdirs() }.writeText(
        """
        |-tester: biz.aQute.tester.junit-platform
        |-runfw: org.apache.felix.framework
        |-runee: $runee
        |
        |-runrequires: \
        |  bnd.identity;id='$bsn',\
        |  bnd.identity;id='junit-jupiter-engine',\
        |  bnd.identity;id='junit-platform-launcher'$extraEntries
        """.trimMargin() + systemPackagesContent.get() + "\n",
      )
    }
  }

  val resolvedBndrun = layout.buildDirectory.file("$suiteName.bndrun")

  val resolveTask = tasks.register<Resolve>("${suiteName}Resolve") {
    dependsOn(bundleTask, generateBndrunTask)
    description = "Resolve $suiteName OSGi suite"
    group = JavaBasePlugin.VERIFICATION_GROUP
    bndrun = inputBndrun.get().asFile
    outputBndrun = resolvedBndrun
    bundles = files(sourceSet.runtimeClasspath, bundleTask.get().archiveFile)
    // The generated output embeds an absolute path to the source bndrun, making it unsafe to share
    // across machines or worktrees via the build cache.
    outputs.cacheIf { false }
  }

  if (resolveOnly) {
    return resolveTask
  }

  return tasks.register<TestOSGi>("testOSGi${suiteName.replaceFirstChar { it.uppercase() }}") {
    description = "OSGi Test $suiteName.bndrun"
    group = JavaBasePlugin.VERIFICATION_GROUP
    bndrun = resolveTask.flatMap { it.outputBndrun }
    bundles = files(sourceSet.runtimeClasspath, bundleTask.get().archiveFile)
    if (minJavaVersion != null) {
      val testJavaVersion: String? by project
      enabled = testJavaVersion == null || testJavaVersion!!.toInt() >= minJavaVersion
    }
    // BND reports success when zero tests ran (e.g. if bundles failed to start). Fail explicitly.
    val testResultsDir = layout.buildDirectory.dir("test-results/$name")
    doLast {
      check(testResultsDir.get().asFile.listFiles()?.isNotEmpty() == true) {
        "No OSGi test results found for suite '$suiteName' - bundles may have failed to start. Check the output above."
      }
    }
  }
}

// Suite: api - core instrumentation API + annotations bundles in isolation.
val apiSuiteTask = registerOsgiSuite("api") {
  implementation(project(":instrumentation-api"))
  implementation(project(":instrumentation-api-incubator"))
  implementation(project(":instrumentation-annotations"))
}

// Suite: apacheHttpClient - a representative library instrumentation bundle, exercised against the
// stock Apache HttpComponents OSGi bundles - the exact same bundles AEM/Sling provide
// (org.apache.httpcomponents.httpclient/httpcore), with commons-logging and Config Admin.
val apacheHttpClientSuiteTask = registerOsgiSuite("apacheHttpClient") {
  implementation(project(":instrumentation:apache-httpclient:apache-httpclient-4.3:library"))
  // httpclient-osgi/httpcore-osgi are the real OSGi bundles (BSN org.apache.httpcomponents.*) - the
  // same ones AEM ships. Pull them non-transitively: their POMs also drag in the plain httpclient/
  // httpcore jars, which are NOT bundles and would shadow the OSGi bundles in the resolver.
  implementation("org.apache.httpcomponents:httpclient-osgi:4.5.14") { isTransitive = false }
  implementation("org.apache.httpcomponents:httpcore-osgi:4.4.16") { isTransitive = false }
  // httpclient imports commons-logging in [1.1,1.3); pin to 1.2 (an OSGi bundle) since
  // dependencyManagement otherwise forces 1.3.6, which is outside that range. In AEM this package
  // is provided by jcl-over-slf4j.
  implementation("commons-logging:commons-logging") {
    version { strictly("1.2") }
  }
  runtimeOnly("org.apache.felix:org.apache.felix.configadmin:1.9.26")
}

// Suite: logbackAppender - a representative library instrumentation bundle, resolving against
// instrumentation-api and the instrumented library. logback-classic is itself an OSGi bundle.
// Also verifies the bundle resolves WITHOUT Logstash present, proving the net.logstash.logback
// optional-import tuning.
val logbackAppenderSuiteTask = registerOsgiSuite("logbackAppender") {
  implementation(project(":instrumentation:logback:logback-appender-1.0:library"))
  implementation("ch.qos.logback:logback-classic")
}

// Suite: resources - the key SPI test. Asserts the AutoService-generated ResourceProvider services
// are mediated by SPI Fly, i.e. the -metainf-services: auto capabilities resolve in OSGi.
val resourcesSuiteTask = registerOsgiSuite(
  "resources",
  // Nothing imports the resources bundle's packages (the test inspects the OSGi service registry),
  // so force it into the runtime. BSN = archivesName from otel.java-conventions.
  extraRunrequires = listOf("opentelemetry-resources"),
) {
  implementation(project(":instrumentation:resources:library"))
  implementation("io.opentelemetry:opentelemetry-sdk")
  implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi")
}

tasks {
  jar {
    enabled = false
  }
  test {
    // Replace junit testing with the testOSGi tasks: clear test actions and depend on all suites,
    // so running :test runs every OSGi suite.
    actions.clear()
    dependsOn(
      apiSuiteTask,
      apacheHttpClientSuiteTask,
      logbackAppenderSuiteTask,
      resourcesSuiteTask,
    )
  }
}

// Skip ossIndexAudit on test module.
tasks.named("ossIndexAudit") {
  enabled = false
}
