file_format: "0.4"
tracer_provider:
  processors:
    - simple:
        exporter:
          test_bridge:
    - simple:
        exporter:
          console:

logger_provider:
  processors:
    - simple:
        exporter:
          test_bridge:

meter_provider:
  readers:
    - periodic:
        # Set really long interval. We'll call forceFlush when we need the metrics
        # instead of collecting them periodically.
        interval: 1000000
        exporter:
          test_bridge:

instrumentation/development:
  java:
    methods:
      include:
        - class: io.opentelemetry.javaagent.instrumentation.methods.MethodTest$ConfigTracedCallable
          methods:
            - name: call
        - class: io.opentelemetry.javaagent.instrumentation.methods.MethodTest$ConfigTracedCompletableFuture
          methods:
            - name: getResult
              span_kind: SERVER
        - class: javax.naming.directory.InitialDirContext
          methods:
            - name: search
              span_kind: CLIENT
