/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.javaagent.instrumentation.spring.gateway.v2_0;

import io.opentelemetry.api.common.AttributeKey;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.context.Context;
import io.opentelemetry.instrumentation.api.instrumenter.LocalRootSpan;
import io.opentelemetry.javaagent.bootstrap.internal.AgentInstrumentationConfig;
import java.lang.reflect.Method;
import java.net.URI;
import java.util.Optional;
import java.util.regex.Pattern;
import javax.annotation.Nullable;

/**
 * Helper class for extracting Spring Cloud Gateway Server WebMVC route information from
 * ServerRequest and adding it to spans.
 */
final class ServerRequestHelper {

  /** Route ID attribute key. */
  private static final AttributeKey<String> ROUTE_ID_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.id");

  /** Route URI attribute key. */
  private static final AttributeKey<String> ROUTE_URI_ATTRIBUTE =
      AttributeKey.stringKey("spring-cloud-gateway.route.uri");

  private static final boolean CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES;

  static {
    CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES =
        AgentInstrumentationConfig.get()
            .getBoolean(
                "otel.instrumentation.spring-cloud-gateway.experimental-span-attributes", false);
  }

  /* Regex for UUID */
  private static final Pattern UUID_REGEX =
      Pattern.compile(
          "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

  // WebMVC variant uses these attribute keys (see MvcUtils class)
  private static final String GATEWAY_ROUTE_ID_ATTR = "GatewayServerMvc.gatewayRouteId";
  private static final String GATEWAY_REQUEST_URL_ATTR = "GatewayServerMvc.gatewayRequestUrl";

  private ServerRequestHelper() {}

  public static void extractAttributes(Object request, Context context) {
    if (!CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES) {
      return;
    }

    try {
      System.out.println(
          "[DEBUG] ServerRequestHelper.extractAttributes called with request: "
              + request.getClass().getName());

      Span serverSpan = LocalRootSpan.fromContextOrNull(context);
      if (serverSpan == null) {
        System.out.println("[DEBUG] No server span found");
        return;
      }

      // Use reflection to get attributes from ServerRequest
      Method attributeMethod = request.getClass().getMethod("attribute", String.class);

      // Get route ID
      Optional<?> routeIdOpt = (Optional<?>) attributeMethod.invoke(request, GATEWAY_ROUTE_ID_ATTR);
      System.out.println(
          "[DEBUG] routeId present: " + (routeIdOpt != null && routeIdOpt.isPresent()));
      if (routeIdOpt != null && routeIdOpt.isPresent()) {
        String routeId = (String) routeIdOpt.get();
        if (routeId != null) {
          serverSpan.setAttribute(ROUTE_ID_ATTRIBUTE, routeId);
          System.out.println("[DEBUG] Set route ID: " + routeId);
        }
      }

      // Get request URL (the target URI set by uri() filter)
      Optional<?> requestUrlOpt =
          (Optional<?>) attributeMethod.invoke(request, GATEWAY_REQUEST_URL_ATTR);
      System.out.println(
          "[DEBUG] requestUrl present: " + (requestUrlOpt != null && requestUrlOpt.isPresent()));
      if (requestUrlOpt != null && requestUrlOpt.isPresent()) {
        URI uri = (URI) requestUrlOpt.get();
        if (uri != null) {
          serverSpan.setAttribute(ROUTE_URI_ATTRIBUTE, uri.toASCIIString());
          System.out.println("[DEBUG] Set route URI: " + uri.toASCIIString());
        }
      }

      // Note: WebMVC variant doesn't store route order or filters in attributes
      // Only route ID and request URL are available
    } catch (Exception e) {
      System.out.println("[DEBUG] Exception in extractAttributes: " + e.getMessage());
      e.printStackTrace();
      // Silently ignore - classes may not be present
    }
  }

  @Nullable
  public static String extractServerRoute(@Nullable Object request) {
    if (request == null) {
      return null;
    }

    try {
      Method attributeMethod = request.getClass().getMethod("attribute", String.class);
      Optional<?> routeIdOpt = (Optional<?>) attributeMethod.invoke(request, GATEWAY_ROUTE_ID_ATTR);

      if (routeIdOpt != null && routeIdOpt.isPresent()) {
        String routeId = (String) routeIdOpt.get();
        return convergeRouteId(routeId);
      }
    } catch (Exception e) {
      // Silently ignore
    }
    return null;
  }

  /** To avoid high cardinality, we ignore random UUID generated by Spring Cloud Gateway. */
  @Nullable
  private static String convergeRouteId(String routeId) {
    if (routeId == null || routeId.isEmpty()) {
      return null;
    }
    if (UUID_REGEX.matcher(routeId).matches()) {
      return null;
    }
    return routeId;
  }
}
