name: PR build early jdk8 images for smoke tests

on:
  pull_request:
    paths:
      - "smoke-tests/images/early-jdk8/**"
      - ".github/workflows/pr-smoke-test-early-jdk8-images.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: true

      - name: Build Docker image
        run: ./gradlew :smoke-tests:images:early-jdk8:imageBuild
