name: Publish fake backend images for smoke tests

on:
  push:
    paths:
      - "smoke-tests/images/fake-backend/**"
      - ".github/workflows/publish-smoke-test-fake-backend-images.yml"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publishLinux:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Login to GitHub package registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build Docker image
        run: ./gradlew :smoke-tests:images:fake-backend:jib -Djib.httpTimeout=120000 -Djib.console=plain -PextraTag=${{ env.TAG }}

  publishWindows:
    permissions:
      contents: read
      packages: write
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Support long paths
        run: git config --system core.longpaths true

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Login to GitHub package registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build Docker image
        run: ./gradlew :smoke-tests:images:fake-backend:dockerPush -PextraTag=${{ env.TAG }}

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - publishLinux
      - publishWindows
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: >-
        ${{
          needs.publishLinux.result == 'success' &&
          needs.publishWindows.result == 'success'
        }}
