name: Publish gRPC images for smoke tests

on:
  push:
    paths:
      - "smoke-tests/images/grpc/**"
      - ".github/workflows/publish-smoke-test-grpc-images.yml"
      - ".github/workflows/reusable-publish-smoke-test-images.yml"
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-publish-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:grpc"

  workflow-notification:
    permissions:
      issues: write
    needs:
      - publish
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@03559ef555db0eae5d85c3c6347d1530243e7aa7 # v0.13.0
    with:
      success: ${{ needs.publish.result == 'success' }}
