name: Publish PetClinic benchmark image
on:
  push:
    paths:
      - "benchmark-overhead/Dockerfile.petclinic"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to GitHub container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create timestamp for docker image tag
        run: echo "TS=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Push to GitHub packages
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          file: benchmark-overhead/Dockerfile.petclinic
          tags: ghcr.io/open-telemetry/opentelemetry-java-instrumentation/petclinic-rest-base:${{ env.TS }}

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - publish
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
