name: Publish early jdk8 images for smoke tests

on:
  push:
    paths:
      - "smoke-tests/images/early-jdk8/**"
      - ".github/workflows/publish-smoke-test-early-jdk8-images.yml"
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Login to GitHub package registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Build Docker image
        run: ./gradlew :smoke-tests:images:early-jdk8:dockerPush -PextraTag=${TAG}

  workflow-notification:
    permissions:
      issues: write
    needs:
      - publish
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
    with:
      success: ${{ needs.publish.result == 'success' }}
