name: Publish Security Manager test app images for smoke tests

on:
  push:
    paths:
      - "smoke-tests/images/security-manager/**"
      - ".github/workflows/publish-smoke-test-security-manager-images.yml"
      - ".github/workflows/reusable-publish-smoke-test-images.yml"
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-publish-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:security-manager"

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - publish
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
