name: Build on test labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  trigger-build:
    # Only run if one of the test labels was added
    if: |
      github.event.label.name == 'test openj9' ||
      github.event.label.name == 'test windows' ||
      github.event.label.name == 'test native'
    uses: ./.github/workflows/build-pull-request.yml
