# This action updates the CloudFoundry java-buildpack release index after each release.
# See https://github.com/cloudfoundry/java-buildpack/blob/main/docs/extending-repositories.md
# Prerequisite: the repo must have a branch named "cloudfoundry".

name: Update cloudfoundry release index
on:
  schedule:
    - cron: '25 4 * * *' # Daily at 4:25 AM UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-cloudfoundry-index-yml:
    permissions:
      contents: write # for git push to PR branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

        # need to run this script before we switch branches
        # since the script doesn't exist on the cloudfoundry branch
      - name: Use CLA approved github bot
        run: .github/scripts/use-cla-approved-bot.sh

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: 'cloudfoundry'
          persist-credentials: false

      - name: create working branch
        run: git checkout -b otelbot/cloudfoundry-${{ github.run_number }}-${{ github.run_attempt }}

      - name: update index.yml
        run: |
          wget https://repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/maven-metadata.xml
          grep -oP '(?<=<version>)[^<]+' maven-metadata.xml | sed -E 's/(.*)/\1: https:\/\/repo1.maven.org\/maven2\/io\/opentelemetry\/javaagent\/opentelemetry-javaagent\/\1\/opentelemetry-javaagent-\1.jar/' > index.yml

      - name: display changes
        run: git diff

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: otelbot-token
        with:
          client-id: ${{ vars.OTELBOT_CLIENT_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
          permission-pull-requests: write

      - name: create pr with repo changes
        env:
          # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
        run: |
          git add index.yml
          if git diff-index --quiet --cached HEAD ; then
            echo "index.yml already current"
            exit 0
          fi
          git commit -m "Updated index.yml"
          git push --set-upstream origin otelbot/cloudfoundry-${{ github.run_number }}-${{ github.run_attempt }}
          gh pr create --base cloudfoundry \
            --head otelbot/cloudfoundry-${{ github.run_number }}-${{ github.run_attempt }} \
            --title 'Release updates for Cloudfoundry Repo' \
            --body '[Created by Github action]'

  workflow-notification:
    permissions:
      issues: write
    needs:
      - update-cloudfoundry-index-yml
    if: always()
    uses: open-telemetry/shared-workflows/.github/workflows/workflow-failure-issue.yml@62d5939b47144252763c5ff9fffe8c20d76cd806 # v0.4.0
    with:
      success: ${{ needs.update-cloudfoundry-index-yml.result == 'success' }}
