otel:
  # "file_format" serves as opt-in to the new file format
  file_format: "0.4"
  tracer_provider:
    processors:
      - simple:
          exporter:
            test_bridge:
      - simple:
          exporter:
            console:

  logger_provider:
    processors:
      - simple:
          exporter:
            test_bridge:

  meter_provider:
    readers:
      - periodic:
          # Set really long interval. We'll call forceFlush when we need the metrics
          # instead of collecting them periodically.
          interval: 1000000
          exporter:
            test_bridge:

  propagator:
    composite:
      - tracecontext:
      - baggage:

  instrumentation/development:
    java:
      runtime-telemetry:
        emit-experimental-telemetry: true
      http:
        client:
          emit-experimental-telemetry: true
