otel:
  # "file_format" serves as opt-in to the new file format
  file_format: "0.4"
  tracer_provider:
    processors:
      - simple:
          exporter:
            otlp_http:

  logger_provider:
    processors:
      - simple:
          exporter:
            otlp_http:

  meter_provider:
    readers:
      - periodic:
          interval: 1000
          exporter:
            otlp_http:

  resource:
    attributes:
      - name: foo
        value: bar
